#!/bin/bash

# Thanks to https://github.com/Nariri
# 2024-02-27 16:40:03
PATH=/sbin:/usr/sbin:/bin:/usr/bin
MODPROBE_LIST=`find /lib/modules/$(uname -r) -type f -name *.ko* -exec bash -c 'echo {} | rev | cut -f1 -d '/' | rev | cut -f1 -d '.'' \;`

# https://unix.stackexchange.com/questions/9784/how-can-i-read-line-by-line-from-a-variable-in-bash
while IFS= read -r line
do
	NAME=`echo $line | tr -d '\n' | tr -d '\r'`
	sudo timeout --signal=9 1s modprobe -r $NAME && sudo timeout --signal=9 1s modprobe $NAME &
done < <(printf '%s\n' "$MODPROBE_LIST")
